sudo: false
language: rust
branches:
  only:
  - master

cache: cargo

matrix:
  fast_finish: false
  include:
  - rust: stable
  # - rust: beta
  # - rust: nightly

addons:
  apt:
    packages:
      - libudev-dev
      - libssl-dev
      - pkg-config

script:
  - cargo build --all
  - cargo test --all
